# Generated by Django 5.1 on 2024-09-25 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_course_instructor_alter_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
