# Generated by Django 5.1 on 2024-09-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_course_instructor_alter_course_users'),
        ('instructorcalendar', '0003_alter_course_instructor_alter_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
