# Generated by Django 5.1 on 2024-09-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorcalendar', '0005_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
