# Generated by Django 5.1 on 2024-09-25 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorcalendar', '0006_delete_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='students',
            field=models.ManyToManyField(related_name='class_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='students',
            field=models.ManyToManyField(related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
